### PR TITLE
Add page for the 2022 tracing summit

### PR DESCRIPTION
**Pull request by chromy**
Draft for the 2022 tracing summit page. I also added a note to the front page.

### CODE REVIEW

**Comment by chromy** [comment]
@primiano fyi

**Comment by compudj** [comment]
It looks good to me ! Let me know if we should deploy it now.

**Comment by mjeanson** [comment]
The 2022 page you added could just replace the current main page.

**Comment by chromy** [comment]
@mjeanson Thanks! I've updated the PR.

@compudj Thanks! Now is good by me, also from my side feel free to send the [announcement email we drafted](https://docs.google.com/document/d/1wxKrgWUCGqp7X3K-LW1VpIfDSMTHIqIkjQbFB9cV3ks/edit?usp=sharing&resourcekey=0-ldFm2NhvApVA_sYRnede2g) whenever you are ready. I filled in the dates which I think were the last thing outstanding. Let me know if there is anything else we should resolve before hand :)

**Pull request merged**
